### ISSUE TITLE
singin != signin

### ISSUE THREAD

**Issue by n3uz** [zhuima/daohang#1]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/zhuima/daohang/CONTRIBUTING.md)**，严格遵循其约定。

# 错误报告

后台登录地址 singin != signin 英语癌

daohang/urls.py  

```
url(r'^singin/', admin.site.urls, name='login'),
```

**Comment by zhuima** [comment]
感谢你的发现，已修正，相见https://github.com/zhuima/daohang/blob/master/CHANGELOG.md
