### ISSUE TITLE
window系统，git clone https://github.com/zhuima/daohang.git 报错

### ISSUE THREAD

**Issue by tobensun** [zhuima/daohang#20]
$ git clone https://github.com/zhuima/daohang.git
Cloning into 'daohang'...
remote: Enumerating objects: 147, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (17/17), done.
Receivremote: Total 147 (delta 9), reused 20 (delta 7), pack-reused 122
Receiving objects: 100% (147/147), 584.57 KiB | 180.00 KiB/s, done.
Resolving deltas: 100% (62/62), done.
error: invalid path 'static/app/fonts/iconfont.ttf?t=1490497072'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by tobensun** [comment]
**error: invalid path 'static/app/fonts/iconfont.ttf?t=1490497072'**

**Comment by zhuima** [comment]
这应该是qiang的问题吧
