### ISSUE TITLE
登录界面显示异常

### ISSUE THREAD

**Issue by Ramboooooooo** [zhuima/daohang#22]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/zhuima/daohang/CONTRIBUTING.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

http://localhost:8080/signin

## 你期望的结果是什么？

正确显示登录界面

## 实际结果是什么？

登录界面 显示不全，css 和 js 错误

**Comment by 30Curry** [comment]
我也出现了，以前没这情况啊，什么鬼

**Comment by zhuima** [comment]
应该是兼容性问题，我这周修复下

**Comment by 30Curry** [comment]
老大，修复了吗

**Comment by 30Curry** [comment]
> 应该是兼容性问题，我这周修复下
老大，修复了吗

**Comment by Ramboooooooo** [comment]
> 

zhuima ，could you finished ？

**Comment by zhuima** [comment]
问题已经修复，重新拉下代码构建下即可

**Comment by zhuima** [comment]
> 我也出现了，以前没这情况啊，什么鬼

依赖的django-simpleui版本 官方直接升级到了2022.4.9
