### ISSUE TITLE
更新后，不管是直接拉镜像起，还是构建镜像起，容器里的web服务没有运行起来

### ISSUE THREAD

**Issue by 30Curry** [zhuima/daohang#26]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/zhuima/daohang/CONTRIBUTING.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

之前版本后台管理页面登陆不了，这两天看到已修复。重新部署
第一种方法 docker pull ghcr.io/zhuima/daohang  docker-compose up
第二种方法 自行构建docker镜像 

## 你期望的结果是什么？

daohang能够正常显示页面

## 实际结果是什么？

daohang页面打不开，telnet服务器+端口 提示连接被拒  服务器上ss -nltp 可以看到8080在监听 进入到docker容器里ss -nltp 没有发现8080在工作

**Comment by zhuima** [comment]
问题修复，你可以自己本地构建，或者直接使用最新的镜像，或者使用我上传到hub的镜像 docker pull zhuima314/daohang:v0.0.7
