### ISSUE TITLE
跑起来了， 后台无法登录  

### ISSUE THREAD

**Issue by changchunhua2017** [zhuima/daohang#28]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/zhuima/daohang/CONTRIBUTING.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

docker 部署了 daohang

## 你期望的结果是什么？

后台能登录

## 实际结果是什么？

后台登录界面的用户密码框 根本不显示  

## daohang环境

docker 环境

@zhuima   为啥会这样啊 

![1657177302(1)](https://user-images.githubusercontent.com/32860151/177711942-a4f545c1-f176-42d8-9d28-dffdc55fa661.jpg)

**Comment by zhuima** [comment]
问题修复，你可以自己本地构建，或者直接使用最新的镜像，或者使用我上传到hub的镜像 docker pull zhuima314/daohang:v0.0.7
