### ISSUE TITLE
url_status

### ISSUE THREAD

**Issue by fqtlrq** [zhuima/daohang#3]
Request Method: | POST
-- | --
http://10.240.7.131:8080/commit/
1.8.1
OperationalError
### **table app_urlinfor has no column named url_status**
/usr/local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py in execute, line 318
/usr/local/bin/python
3.5.7
['/usr/local/web',  '/usr/local/lib/python35.zip',  '/usr/local/lib/python3.5',  '/usr/local/lib/python3.5/plat-linux',  '/usr/local/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/site-packages']
星期三, 17 四月 2019 21:02:16 +0800

页面报错，请问这个是什么原因呢

**Comment by zhuima** [comment]
该bug已经修复，请更新最新代码进行测试

**Comment by zhuima** [comment]
表字段不存在
