### ISSUE TITLE
密码不对

### ISSUE THREAD

**Issue by kingsxw** [zhuima/daohang#4]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/zhuima/daohang/CONTRIBUTING.md)**，严格遵循其约定。

# 错误报告
admin:admin无法登录
## 你做了什么？
sqlite3 db.sqlite3
select * from "auth_user";
得到密码加密字符串
pbkdf2_sha256$20000$Dx4pWAzBDPek$3d5DOqAxzEKoc2bhjIyzuOHn36elLYYvB+WOMPBEGxA=
通过python验证
>>> check_password("admin","pbkdf2_sha256$20000$Dx4pWAzBDPek$3d5DOqAxzEKoc2bhjIyzuOHn36elLYYvB+WOMPBEGxA=")
False

我修改了后台管理界面

## 你期望的结果是什么？
True
daohang能够提供更炫酷的页面，可以拿得出手。

## 实际结果是什么？
False

**Comment by kingsxw** [comment]
make_password("XXX", None, 'pbkdf2_sha256')生成一个，然后
update auth_user set password='pbkdf2_sha256XXX' where id=1;更新以后就能登录了

**Comment by zhuima** [comment]
也有可能是我初始化的时候生成了admin:zhuima, 你可以看下

至于前端页面这个如果有时间会更新，感谢你的建议

**Comment by kingsxw** [comment]
页面那个是模板里自带的话，选的时候没选中也就没删掉。。。
