### ISSUE TITLE
部署太麻烦了

### ISSUE THREAD

**Issue by liujiaxian** [zhuima/daohang#5]
第一种部署太麻烦了
第二种docker我没试

**Comment by liujiaxian** [comment]
密码不知道是什么鬼，百度了一个，覆盖数据库密码，这个密码是 abc,进去后台，编辑导航报错
pbkdf2_sha256$2000$good_salt$xDb4PWMWoQengkNyzh1IU3jGkZWK+BKManvkeJPunVQ=

**Comment by zhuima** [comment]
这个我修改下
