### ISSUE TITLE
请问这个后台的用户密码是什么？

### ISSUE THREAD

**Issue by somebdly** [zhuima/daohang#6]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/zhuima/daohang/CONTRIBUTING.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

我修改了后台管理界面

## 你期望的结果是什么？

daohang能够提供更炫酷的页面，可以拿得出手。

## 实际结果是什么？

daohang页面太过于简陋

### Docker

我用admin:admin登陆不进去

**Comment by somebdly** [comment]
另外docker-compose.yml文件里面的端口是不是写错了。
    ports:
      - 8080:8000
看起来应该是8080:8080才对，我用这个端口才能正常访问

**Comment by somebdly** [comment]
我自己重新创建了管理员。已经进去了。

**Comment by zhuima** [comment]
admin:zhuima
