### ISSUE TITLE
daohang\settings.py

### ISSUE THREAD

**Issue by 30Curry** [zhuima/daohang#8]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/zhuima/daohang/CONTRIBUTING.md)**，严格遵循其约定。

# 错误报告
访问web报错   You may need to add ip to ALLOWED_HOSTS
## 你做了什么？
修改daohang\settings.py文件，ALLOWED_HOSTS = ['*']
### vm或物理机器
VM
### Docker
Docker

**Comment by zhuima** [comment]
如果用Docker的话不会存在这个问题，我后续调整下
